### ISSUE TITLE
Is there a way to use a Field TypeormLoader for a computed Field?

### ISSUE THREAD

**Issue by dickfickling** [slaypni/type-graphql-dataloader#12]
Brief example:
```typescript
@Entity()
@ObjectType()
export default class User {
  @Field()
  id!: string;

  @Field(() => [Post])
  @TypeormLoader(() => Post, (post: Post) => post.userId, {
    selfKey: true,
  })
  @OneToMany(() => Post, (post) => post.user)
  posts?: Post[];
}
```
```typescript
@Resolver(() => User)
export default class UserResolver {
  @FieldResolver(() => Number)
  async numPosts(@Root() user: User): Promise<number> {
    // currently using:
    await user.reload({ relations: ["posts"] });
    return user.posts!.length;
    // would like to somehow use the user posts resolver to batch, something like:
    return (await User.dataloader.load(user.id)).length;
 }
}
```

Is this possible? I understand the example is a bit contrived. I know I can use a custom `@Loader` in my `numPosts` FieldResolver, but it'd be great if I can take advantage of the existing DataLoader from the model declaration.

thanks!

Edit: I should add, I'm so stoked you wrote this short but powerful library. It's made my life so much easier.

**Comment by slaypni** [comment]
I did not imagine that kind of use cases. Accessing internal dataloader would be technically possible, however it is not recommended and prone to not work in future updates. There is no official way to achieve it at this moment.

\*Unofficial way\* You could get the dataloader from `Container` by passing the name that this library is using. ([ref](https://github.com/slaypni/type-graphql-dataloader/blob/75dfb1e785a8e330a62e487d08c71aa7b6fbabd1/src/decorators/typeorm/TypeormLoader.ts#L105-L109))

**Comment by dickfickling** [comment]
Not a big deal; i can continue using a custom Loader. Feel free to close this issue unless you feel like this is a feature worth building.

**Comment by slaypni** [comment]
All right, I think that it is a legitimate way to use `@Loader` for this case, and internal dataloader used for `@TypeormLoader` does not suit to be exposed. Thank you for posing this issue.
