### ISSUE TITLE
Some problems encountered when using the library

### ISSUE THREAD

**Issue by x-shadow-x** [slaypni/type-graphql-dataloader#29]
## describe
Today, I used this library when optimizing an n+1 problem of graphql. After adding the corresponding code according to the document, I got an `'data.context._tgdContext' as it is undefined` error. It took me almost an afternoon to troubleshoot the problem. Finally found that this problem is caused by the version of `apollo-server-express`. I originally wanted to submit a pr to update the readme, but it seems that I don’t have the relevant permissions, so I can only raise an issue. Hope you can record the corresponding problem in the document for subsequent developers. At present, only `apollo-server-express` version 3 can make the latest version of `type-graphql-dataloader` run, but I believe there are still many developers who use `apollo-server-express` version 2. Using version 2 will cause an error, and `'data.context._tgdContext' as it is undefined` is almost of no help in solving this error

## issues

1. 'data.context._tgdContext' as it is undefined
```
"TypeError: Cannot destructure property 'requestId' of 'data.context._tgdContext' as it is undefined.",
"    at /var/app/node_modules/type-graphql-dataloader/dist/decorators/Loader.js:14:21",
"    at dispatchHandler (/var/app/node_modules/type-graphql/dist/resolvers/helpers.js:82:30)",
"    at Object.applyMiddlewares (/var/app/node_modules/type-graphql/dist/resolvers/helpers.js:88:12)",
"    at /var/app/node_modules/type-graphql/dist/resolvers/create.js:27:26",
```
- please check if `ApolloServerLoaderPlugin` is added when you new Apolloserver instance
- check the version of `apollo-server-express`, if you use version2 then please use a lower version of `type-graphql-dataloader`, such as 0.3.2.

**Comment by slaypni** [comment]
Please stick with `type-graphql-dataloader` 0.4.1 since Apollo Server 2 support was dropped in 0.5.0.
https://github.com/slaypni/type-graphql-dataloader/releases/tag/v0.5.0

Adding that information in README would be good idea. Thanks
