### ISSUE TITLE
Problem with yarn install/build @types of module 'vfile-message' missing

### ISSUE THREAD

**Issue by agustif** [slaypni/type-graphql-dataloader#3]
when I run yarn to install deps, the build fails due to vfile-message types missing?
  Try `npm install @types/vfile-message` if it exists or add a new declaration (.d.ts) file containing `declare module 'vfile-message';`

11 import * as vfileMessage from 'vfile-message';
                                 ~~~~~~~~~~~~~~~

Maybe my node env is broken or something
```bash
➜ y
[!!]y
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ npm run-script clean && npm run-script build

> type-graphql-dataloader@0.1.0 clean /Users/agustif/Code/type-graphql-dataloader
> rimraf dist


> type-graphql-dataloader@0.1.0 build /Users/agustif/Code/type-graphql-dataloader
> tsc -p tsconfig.build.json

../../node_modules/@types/vfile/index.d.ts:11:31 - error TS7016: Could not find a declaration file for module 'vfile-message'. '/Users/agustif/node_modules/vfile-message/index.js' implicitly has an 'any' type.
  Try `npm install @types/vfile-message` if it exists or add a new declaration (.d.ts) file containing `declare module 'vfile-message';`

11 import * as vfileMessage from 'vfile-message';
                                 ~~~~~~~~~~~~~~~

Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! type-graphql-dataloader@0.1.0 build: `tsc -p tsconfig.build.json`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the type-graphql-dataloader@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/agustif/.npm/_logs/2020-08-08T13_08_29_228Z-debug.log
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by slaypni** [comment]
I run `yarn list | grep 'vfile'` and it returned no output. Therefore `vfile` seems not related to `type-graphql-dataloader`.

Your error message contains `../../node_modules/@types/vfile/index.d.ts`. Is it the case that there is `node_modules/` at parent directory? If so, tsconfig might be misconfigured so that build looks for it.

**Comment by slaypni** [comment]
BTW I updated `package.json` so that `npm run-script build` won't be running when running `npm install` anymore.

**Comment by agustif** [comment]
Yeah after git pull and rm -rf node modules folder from my user root folder all working good. Thanks
