### ISSUE TITLE
Cannot read properties of undefined (reading 'typeormGetConnection')

### ISSUE THREAD

**Issue by jronnybravo** [slaypni/type-graphql-dataloader#32]
```
import "reflect-metadata";
import { ApolloServer } from "apollo-server-express";
import { ApolloServerLoaderPlugin } from "type-graphql-dataloader";

import * as Express from "express";
import { buildSchema } from "type-graphql";
import { createConnection, getConnection } from "typeorm";

import { UserResolver } from "./resolvers/UserResolver";
import { VideoResolver } from "./resolvers/VideoResolver";


(async () => {
    await createConnection().then(() => {
        console.log("started");
    });

    const app = Express();
    const apollo = new ApolloServer({
        schema: await buildSchema({
            resolvers: [UserResolver, VideoResolver]
        }),
        plugins: [
            ApolloServerLoaderPlugin({
                typeormGetConnection: getConnection,
            }),
        ],
    });

    apollo.applyMiddleware({ app });
        app.listen(4000, () => {
        console.log("server started on http://localhost:4000/graphql");
    });
})();
``` 

This returns "Cannot read properties of undefined (reading 'typeormGetConnection')" issue when I'm pulling up the relation field. Is Express affecting it?

**Comment by slaypni** [comment]
Is it related to #31?

**Comment by jronnybravo** [comment]
@slaypni seems to be the case... But this one seems to be built around express specifically.

**Comment by jronnybravo** [comment]
@slaypni do we have any boilerplate projects that is able to run `type-graphql-dataloader` correctly. I was thinking it would be best to just start from there...

**Comment by slaypni** [comment]
If you are looking for an example that works, `examples/typeorm` in this repository is available.

**Comment by jronnybravo** [comment]
Thanks. As it turns out it's my outdated packages that is causing the issue. I'm closing this for now.

**Comment by codechrysalis-doug** [comment]
I am getting this error, but not really sure why.

@jronnybravo What packages did you update?

**Comment by jronnybravo** [comment]
@codechrysalis-doug I've just copied all the packages from `examples/typeorm`. Hope this helps.
