### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by signinit** [slaypni/type-graphql-dataloader#6]
Hey, i am currently encountering an caching issue, caused by the dataloader, which is caching the requests automatically.
This is less of an issue and more of an feature request, to be able to configure caching, either per relation or at start.
I disabled caching by inserting an "clearAll()" after the batch request, but that's not very generic.
From my perspective caching should be configureable somehow

**Comment by slaypni** [comment]
Are you using `@Loader` decorator? It takes `DataLoader.Options` as the second argument. Passing it setting `cache` option may solve your situation.

**Comment by signinit** [comment]
Yeah I thought of that too, but wouldn't that cause a lot of overhead in my code, since I always would have to specify a custom batchLoaderFn, which TypeormLoader does for me?
I will have to do that if there is no other option but I just wanted to ask if their could be a better option (in the future) 😄

**Comment by slaypni** [comment]
Does adding `DataLoader.Options` to `TypeormLoader` solves your problem?
It is possible, however, I am not sure in what kind of cases it would be useful.
BTW, using `Loader` with `BatchLoadFn` itself does not cause more overhead than `TypeormLoader`.

**Comment by signinit** [comment]
I didn't find a way to replicate the logic of TypeormLoader with Loader easily.
How would I write sth like
`@TypeormLoader((type) => Group, (group: Group) => group.parentId)`
with `Loader` without rewriting the logic you implemented in TypeormLoader?

Passing DataLoader.Options via TypeormLoader would solve my caching problem i guess, but would cause the system to make multiple requests on duplicate entries i think (what i understood from the dataloader description).
A custom callback per TypeormLoader or per ApolloServerLoaderPlugin would be awesome in my case, so i can call .clearAll() after each batch request on the specific dataloader instance.
Thanks for your time btw :-)

**Comment by slaypni** [comment]
What kind of relation are you using with `@TypeornLoader`? In case of `ManyToOne` the field resolver  can be like below:

```typescript
@Resolver((of) => Group)
export class GroupResolver {
  @FieldResolver()
  @Loader<number, Parent>(async (ids) => {  // batchLoadFn
    const repository = getRepository(Parent);
    const parents = keyBy(await repository.findByIds(ids), "id");
    return ids.map((id) => parents[id]);
  })
  parent(@Root() root: Group) {
    return (dataloader: DataLoader<number, Parent>) =>
      dataloader.load(root.parentId);
  }
}
```

The code could be a bit different depending on the type of relation.

BTW I would like to know why you want to clear cache for each call of the field if possible.

**Comment by signinit** [comment]
Thanks for the code, I can probably solve my issue with that.

My problem:
When I edit the database, my application wont show the current data, because the dataloader is caching the old db entries so I need to somehow prevent caching without loosing too much performance.
So I read in the "Disable caching" section from dataloader
https://github.com/graphql/dataloader#disabling-cache
that a solution would be to clear the cache after each request.

**Comment by slaypni** [comment]
It seems you may not need to clear cache because `type-graphql-dataloader` assigns individual dataLoader for each request.
