### ISSUE TITLE
TS Error with later versions of apollo-server-express and typeorm

### ISSUE THREAD

**Issue by geoyws** [slaypni/type-graphql-dataloader#7]
You can reproduce it by installing the latest version of `apollo-server-express` and `typeorm`.

```TypeScript
const apolloServer = new ApolloServer({
    schema,
    context: ({ req, res }: any) => ({ req, res, conn }),
    plugins: [
        ApolloServerLoaderPlugin({
            typeormGetConnection: getConnection
        })
    ]
});
```

**Comment by slaypni** [comment]
@geoyws I tried to run it, however did not see any errors when running `tsc -b`. Installed packages are:
```
    "apollo-server-express": "^2.18.2",
    "type-graphql": "^1.1.0",
    "type-graphql-dataloader": "^0.2.1",
    "typeorm": "^0.2.28"
```

What errors did you get?

**Comment by geoyws** [comment]
Basically it's a type issue with typeormGetConnection. Had to downgrade to your tested versions of TypeORM and apollo-server-express. Didn't take a snapshot. Will try it again. Sorry, really held up with work.

**Comment by slaypni** [comment]
I think the problem has been fixed by the new version.
https://github.com/slaypni/type-graphql-dataloader/releases/tag/v0.3.2

If it was not, please reopen the issue.
