### ISSUE TITLE
Context support?

### ISSUE THREAD

**Issue by twk** [slaypni/type-graphql-dataloader#9]
I'm not sure if I'm just missing something, but is there support for passing `Ctx` objects to the batch load function?  All of my database access is done via a `Ctx` option that is passed to my `FieldResolver`, but I can't figure out how to give that to my batch function. 

Some sample code:

```
  @FieldResolver(() => Group)
  @Loader<Member, Group>(
    async (member) => {
      // I need the dbGateway here to run my queries
    }
  )
  async group(
    @Root() root: Member,
    @Ctx('db') dbGateway: DbGateway
  ) {
    return (dataLoader: DataLoader<Member, Group>) => {
      return dataLoader.load(root);
    };
  }
```

**Comment by slaypni** [comment]
@twk Thank you for the issue. I have upgraded to have the feature. With the new version, it can be written like:

```ts
  @FieldResolver(() => Group)
  @Loader<Member, Group>(
    async (members, { context }) => {
      // Use context.dbGateway
    }
  )
  async group(@Root() root: Member) {
    return (dataLoader: DataLoader<Member, Group>) => {
      return dataLoader.load(root);
    };
  }
```

Please see if it works for you.

**Comment by twk** [comment]
I hooked this up and now I'm getting an internal server error:
```            
"TypeError: Cannot destructure property 'requestId' of 'data.context._tgdContext' as it is undefined.",
"    at /var/app/node_modules/type-graphql-dataloader/dist/decorators/Loader.js:14:21",
"    at dispatchHandler (/var/app/node_modules/type-graphql/dist/resolvers/helpers.js:82:30)",
"    at Object.applyMiddlewares (/var/app/node_modules/type-graphql/dist/resolvers/helpers.js:88:12)",
"    at /var/app/node_modules/type-graphql/dist/resolvers/create.js:27:26",
<snipped>
```

**Comment by slaypni** [comment]
Did you passed `ApolloServerLoaderPlugin` to `ApolloServer`'s `plugins` ?
Also, please upgrade `type-graphql-dataloader` again since I fixed the feature a bit.

**Comment by twk** [comment]
OK, I updated to 0.3.2 and was able to get something working.  

However, in `async (members, { context }) => {`, the context variable type-checks to `var context: {}`.  So, I need some code like this to actually use my gateway:

`const gateway = (context as any).db.dbGateway`

This is better than not having dataloader support, but is there any way to preserve the types of the context objects?

**Comment by slaypni** [comment]
I have changed `context` to have `Record<string, any>` instead of `{}`. Now you can write like:
```ts
const gateway = context.db.dbGateway
```
Perhaps, it is better to write something like:
```ts
async (members, { context }: { context: MyContext }) => {
```
Though this should work, there could have been other ways such as passing context type as generic type somewhere.

**Comment by twk** [comment]
That works, thank you!

**Comment by geoyws** [comment]
@slaypni Hi, really appreciate the work! Could we get an updated docs on the usage of `@Root` and `@Ctx` with `@Loader`?
Examples that we can build ourselves would be awesome!

**Comment by slaypni** [comment]
`root` could be accessible through `context` from `batchLoadFn` by writing like:

```
  @FieldResolver(() => Group)
  @Loader<Member, Group>(
    async (members, { context }) => {
      // Use context.groupRoot
    }
  )
  async group(@Root() root: Member, @Ctx() context: Context,) {
    context.groupRoot = root;
    return (dataLoader: DataLoader<Member, Group>) => {
      return dataLoader.load(root);
    };
  }
```

What kind of TS errors do you get with `BatchLoadFn`?

**Comment by geoyws** [comment]
Thanks for the prompt reply! 
Alright, I have no more TS errors. Sorry I was unfamiliar with the `dataLoader` function signature. So if it's alright to pass anything to `dataLoader.load(foo)` then I suppose I could also do this:

```TypeScript
  @FieldResolver(() => Group)
  @Loader<Member, Group>(
    async ({ root, dbGateway, info }) => {
      // I need the dbGateway here to run my queries
    }
  )
  async group(
    @Root() root: Member,
    @Ctx('db') dbGateway: DbGateway,
    @Info() info: any
  ) {
    return (dataLoader: DataLoader<Member, Group>) => {
      return dataLoader.load({ root, dbGateway, info });
    };
  }
```
Am I correct?

**Comment by slaypni** [comment]
Multiple dataLoader.load() are resulted in a `batchLoadFn` call.  So if you like to write code like you written, it should be like:

```typescript
  interface MyDatum {
    root: member,
    dbGateway: DbGateway,
    info: any
  }

  @FieldResolver(() => Group)
  @Loader<MyDatum, Group>(
    async (data: MyDatum[]) => {
      // I need the dbGateway here to run my queries
    }
  )
  async group(
    @Root() root: Member,
    @Ctx('db') dbGateway: DbGateway,
    @Info() info: any
  ) {
    return (dataLoader: DataLoader<MyDatum, Group>) => {
      return dataLoader.load({ root, dbGateway, info });
    };
  }
```
